# This file stores environment/application settings as key-value pairs.
# File purpose: contains key-value configuration entries.
server.port=8084

spring.datasource.url=jdbc:h2:mem:bookdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=password

spring.web.resources.add-mappings=true

spring.jpa.hibernate.ddl-auto=create-drop
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.thymeleaf.prefix=classpath:/templates/
spring.thymeleaf.suffix=.html

spring.jpa.defer-datasource-initialization=true
spring.sql.init.data-locations=classpath:/sql/sql.sql

server.error.include-stacktrace=never
server.error.include-message=never
server.error.whitelabel.enabled=false

logging.level.root=INFO
logging.level.com.epam.rd.autocode.spring.project=DEBUG

security.jwt.secret=VGhpc0lzQVN1ZmZpY2llbnRseUxvbmdKc3d0U2VjcmV0S2V5Rm9yRGV2RW52
security.jwt.expiration-ms=3600000

