spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/bookstore}
spring.datasource.username=${DB_USER:bookstore}
spring.datasource.password=${DB_PASSWORD:bookstore}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.defer-datasource-initialization=true

spring.sql.init.mode=always
spring.sql.init.data-locations=classpath:/sql/sql.sql

spring.jpa.show-sql=false
spring.h2.console.enabled=false
