version: "3.9"
services:
  db:
    image: postgres:16
    environment:
      POSTGRES_DB: bookstore
      POSTGRES_USER: bookstore
      POSTGRES_PASSWORD: bookstore

  app:
    build: .
    environment:
      DB_URL: jdbc:postgresql://db:5432/bookstore
      DB_USER: bookstore
      DB_PASSWORD: bookstore
    ports:
      - "8084:8084"
    depends_on:
      - db
